- name: Install Nginx
  hosts: default
  become: true
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
  - name: Start nginx
    systemd:
      name: nginx
      state: started
